# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'

target 'Project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks! :linkage => :static

  # Pods for Project
  
  pod 'SJBaseVideoPlayer', :path => '../../SJBaseVideoPlayer'  
end
